name: Cypress

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/'
      - 'cypress/'
      - 'cypress.config.cjs'
      - 'pnpm-lock.yaml'
      - '.github/'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/'
      - 'cypress/'
      - 'cypress.config.cjs'
      - 'pnpm-lock.yaml'
      - '.github/'

concurrency:
  group: cypress-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          EMBED_API_TOKEN: ${{ secrets.EMBED_API_TOKEN }}
        with:
          browser: chrome
          build: pnpm gh-action:build
          start: pnpm gh-action:start
          wait-on: 'http://localhost:3000/tracks/1766030'
          command: pnpm cypress:run
