name: Linting JS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '**.js'
      - 'pnpm-lock.yaml'
      - '.github/'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.js'
      - 'pnpm-lock.yaml'
      - '.github/'

jobs:
  lint-js:
    runs-on: ubuntu-24.04
    name: Eslint
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Run Lint Checks
        run: pnpm lint:js
  type-check:
    runs-on: ubuntu-24.04
    name: TypeScript
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Run Type Checks
        run: pnpm typecheck
